import Navbar from '@/components/Navbar';
import theme from '@/theme';
import { Stack } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import type { Metadata } from "next";
import './globals.css';
import Provider from './Provider';

export const metadata: Metadata = {
  title: "TimeSheet APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Provider>
              <Stack sx={{ minHeight: '100vh' }} >
                <Navbar />
                {children}
              </Stack>
            </Provider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
